name: weather_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.7.0
  dartz: ^0.10.1
  equatable: ^2.0.5
  flutter_bloc: ^8.1.6
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/secrets/
    - assets/fonts/

  fonts:
    - family: Bebas
      fonts:
        - asset: assets/fonts/bebas/BebasNeue-Regular.ttf
    
